// src/i18n/locales/en.ts - English
import { TranslationKeys } from './ja';

export const en: TranslationKeys = {
  lang: { name: 'English', flag: 'en' },
  common: {
    loading: 'Loading...',
    analyzing: 'Analyzing...',
    error: 'An error occurred',
    retry: 'Try again',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    confirm: 'Confirm',
    cancel: 'Cancel',
    home: 'Home',
    settings: 'Settings',
    history: 'History',
    stats: 'Stats',
    share: 'Share',
    notFound: 'Not found',
    resultNotFound: 'Diagnosis result not found',
    backHome: '← Back to Home',
  },
  home: {
    badge: '✦ AI Visual Quiz',
    title: 'Does your taste\n',
    titleAccent: 'match the world?',
    subtitle: 'Swipe to analyze your preferences.\nCompare with other countries, body & age trends.',
    startBtn: 'Start Quiz',
    feature1Label: 'Swipe to Rate',
    feature1Desc: 'Just swipe left or right',
    feature2Label: 'Deep Analysis',
    feature2Desc: 'Global compare, body & age',
    feature3Label: 'Global Compare',
    feature3Desc: 'Accuracy improves over time',
    disclaimer:
      'All visuals are AI-generated fictional adult women (20+). Not related to any real person. For entertainment and preference analysis purposes only.',
    navHistory: 'History',
    navStats: 'Stats',
    navSettings: 'Settings',
    terms: 'Terms',
    privacy: 'Privacy',
    contact: 'Contact',
    copyright: '© 2025 Taste Compass',
  },
  setup: {
    stepLabel: 'STEP 1 OF 2',
    pageTitle: 'Setup',
    pageSub: 'Choose count to start',
    countSection: 'Number of Cards',
    themeSection: 'Theme',
    recommended: 'Rec.',
    approx5min: '~5 min',
    approx8min: '~8 min',
    approx15min: '~15 min',
    startBtn: 'Start',
    themes: {
      all:     { label: 'All Styles',    desc: 'Diverse styles for a broad analysis' },
      natural: { label: 'Natural',       desc: 'Clean, natural, fresh look' },
      cool:    { label: 'Cool',          desc: 'Urban, mode, intellectual vibe' },
      cute:    { label: 'Cute',          desc: 'Idol, feminine, girly style' },
      sexy:    { label: 'Sexy',          desc: 'Glamour, gyaru, alluring look' },
      korean:  { label: 'K-Style',       desc: 'K-beauty & Korean trends' },
      global:  { label: 'Global',        desc: 'Multicultural & Western looks' },
      mature:  { label: 'Mature',        desc: 'Elegant, intellectual, sophisticated' },
      casual:  { label: 'Casual',        desc: 'Sporty, casual, approachable' },
    },
  },
  diagnosis: {
    loading: 'Loading images...',
    progress: '{{current}} / {{total}}',
    likeHint: 'Like',
    skipHint: 'Skip',
    complete: 'Done!',
    calculating: 'Calculating results...',
    swipeHint: 'Swipe to rate',
  },
  result: {
    title: 'Diagnosis Result',
    loading: 'Analyzing your results...',
    yourType: 'Your Preference Type',
    compatibilityLabel: 'Match with the World',
    mainstream: 'Mainstream',
    unique: 'Unique',
    countryRanking: 'Country Preference Ranking',
    countryAffinity: 'Your taste resembles',
    countrySuffix: ' style',
    countryMatch: '{{score}}% match',
    meterSection: 'Preference Meters',
    detailSection: '💡 Detailed Trends',
    ageLabel: 'Preferred Age Group',
    vibeLabel: 'Vibe Type',
    tagSection: '🏷 Tags You Liked',
    shareX: 'Share on 𝕏',
    retryBtn: 'Try Again',
    shareText:
      '[Taste Compass] {{type}}\nWorld match: {{score}}%\nClosest country: {{country}}\nRarity: {{rarity}}\n\n{{analysis}}\n\n#TasteCompass',
    meters: {
      gyaru:        'Gyaru',
      pure:         'Pure',
      sexy:         'Sexy',
      mature:       'Mature',
      intellectual: 'Intellectual',
      global:       'Global',
    },
  },
  nav: {
    home: 'Home',
    diagnosis: 'Diagnosis',
    history: 'History',
    stats: 'Stats',
    settings: 'Settings',
  },
  settings: {
    title: 'Settings',
    language: 'Language',
    languageDesc: 'App display language',
    deleteData: 'Delete Data',
    deleteDataDesc: 'Delete all diagnosis history',
    version: 'Version',
    anonymousInfo: 'Anonymous User Info',
    yourAnonymousId: 'Your Anonymous ID',
    anonymousIdLoading: 'Loading...',
    anonymousSub: '※No personal information is linked. It is securely encrypted and stored locally on your device.',
    aboutService: 'About the Service',
    aboutImagesTitle: 'About Diagnosis Images',
    aboutImagesText: 'All visuals used in this service are fictional adult women (20+) generated by AI. There are no real models or people. We strictly exclude images that appear to be minors and prevent sensitive expressions such as excessive exposure or body emphasis.',
    adsPrivacyTitle: 'Ads & Privacy',
    adsPrivacyText: 'This service is operated at a low cost through ad delivery. No ads are displayed during diagnosis to prevent accidental clicks. Also, we do not track to identify individuals.',
    docsContact: 'Documents & Contact',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    reportLink: 'Report Inappropriate Images / Contact',
    dataDeleteSection: 'Data Deletion & Regeneration',
    regenerateId: 'Regenerate Anonymous ID',
    regenerateIdDesc: 'Issue a completely new ID without inheriting diagnosis history.',
    deleteAllData: 'Delete All History & Data',
    deleteAllDataDesc: 'Permanently delete the history stored on this device and all voting data on the database.',
    regenerateModalTitle: 'Regenerate Anonymous ID?',
    regenerateModalDesc: 'Once switched to a new ID, previous history data cannot be loaded. This action cannot be undone.',
    regenerateConfirm: 'Regenerate',
    deleteModalTitle: 'Delete All Data?',
    deleteModalDesc: 'All history, sessions, and voting data stored on this device and the cloud database will be permanently deleted.',
    deleteConfirm: 'Delete Permanently',
  },
  history: {
    title: 'Diagnosis History',
    loading: 'Loading history...',
    emptyTitle: 'No diagnosis history',
    emptySub: 'Complete a quiz to save your preference history here.',
    startButton: 'Start Quiz',
    detailLink: 'View Details →',
    matchBadge: '{{score}}% Match',
  },
  stats: {
    everyoneTitle: 'Everyone\'s Stats',
    mySummaryTitle: 'Your Analysis Summary',
    rankingTitle: 'Top 10 Favorite Visuals (Like Rate)',
    rankingLoading: 'Collecting rankings...',
    emptyData: 'Not enough data gathered yet',
    emptyDataSub: 'Complete more tests to generate statistics',
    votesCount: '{{count}} votes',
    countries: {
      'all': '🌏 Global',
      'ja': '🇯🇵 Japan',
      'ko': '🇰🇷 Korea',
      'en': '🇺🇸 English Speaking',
      'zhCN': '🇨🇳 China',
      'zhTW': '🇹🇼 Taiwan',
      'es': '🇪🇸 Spanish Speaking',
      'pt': '🇵🇹 Portuguese Speaking',
      'fr': '🇫🇷 France',
      'de': '🇩🇪 Germany',
      'id': '🇮🇩 Indonesia',
      'th': '🇹🇭 Thailand',
      'vi': '🇻🇳 Vietnam',
      'ar': '🇸🇦 Arab World',
      'hi': '🇮🇳 India'
},

    title: 'Stats Data',
    loading: 'Compiling stats...',
    compareTitle: 'Your Preferences (Average)',
    compareStatsBtn: 'Take Quiz to Compare Stats',
    mostType: 'Top Type',
    averageCompatibility: 'Avg Compatibility',
    notDiagnosed: 'No Data',
    notMeasured: 'No Data',
    overallStyleTitle: 'Global Style Popularity (By Like Rate)',
    overallTasteTitle: 'Global Visual Taste Popularity (By Like Rate)',
    popularTagsTitle: 'Trending Tags Ranking',
    styles: {
      natural: 'Natural',
      clean: 'Clean & Pure',
      cool: 'Cool & Urban',
      mode: 'Unique Mode',
      casual: 'Casual',
      feminine: 'Soft Feminine',
      korean: 'Korean Trend',
      office: 'Classy Office',
      mature: 'Sophisticated',
      simple: 'Simple Minimal',
      travel: 'Travel Vibe',
      cafe: 'Cafe Relax',
    },
  },
  contact: {
    title: 'Report / Contact Us',
    subtitle: 'Please report any images that closely resemble real people or contain inappropriate expressions here.',
    labelType: 'Contact Type',
    labelImageId: 'Target Image ID (Optional / If known)',
    labelMessage: 'Message Content (Required)',
    placeholderImageId: 'e.g., 00000000-0000-0000-0000-000000000001',
    placeholderMessage: 'Please describe the specific issue or reasons for the deletion request in detail.',
    errorRequired: 'Please enter the message body.',
    errorSubmit: 'Failed to send. Please try again later.',
    successTitle: 'Submission Completed',
    successDesc: 'Thank you for your report/inquiry. We will review the content and take appropriate actions (such as deactivating or removing images) as quickly as possible.',
    submitting: 'Sending...',
    submit: 'Submit',
    types: {
      inappropriate: 'Report Inappropriate Image',
      inappropriateDesc: 'Contains high exposure or inappropriate visuals',
      resemblance: 'Report Resemblance to Real Person',
      resemblanceDesc: 'Closely resembles a specific real individual or celebrity and request removal',
      other: 'Other Inquiries',
      otherDesc: 'Feedback, bug reports, or other general inquiries to the operators',
    },
  },
  documents: {
    termsTitle: 'Terms of Service',
    privacyTitle: 'Privacy Policy',
    termsContent: `Article 1 (Applicability)
These Terms of Service define the conditions for providing "Taste Compass" (hereinafter "Service") and the relationship of rights and obligations between the Service and users. By using the Service, users are deemed to have agreed to these Terms.

Article 2 (Nature of Service & Disclaimer)
1. All character images displayed in this Service are visuals of "fictional adult women" automatically generated by artificial intelligence (AI) technology, and have no relationship with any real people, models, or celebrities.
2. This Service is an entertainment tool for statistically analyzing and diagnosing user preferences, and is not intended to judge the beauty, ugliness, or superiority of specific individuals. We do not guarantee the accuracy or objectivity of the results.

Article 3 (Target Age)
The content handled by this Service is healthy daily fashion excluding adult expressions, but due to the nature of the Service, use by persons under 18 is not assumed. If under 18 uses, parental consent must be obtained.

Article 4 (Prohibited Acts)
Users must not engage in the following acts:
• Using or sharing diagnosis results or images for the purpose of defaming, discriminating, or slandering specific real individuals.
• Unauthorized access to this Service or putting excessive load on the servers.
• Other acts contrary to public order and morals or deemed inappropriate by the operators.

Article 5 (Response to Inappropriate Images)
If you find an image in this Service that closely resembles a real person or is deemed inappropriate, please report it via the "Contact Us" page. We will review and quickly take actions such as deactivating or removing the image.

Article 6 (Changes to Terms)
Operators may change these Terms at any time. Changed Terms will take effect when posted on this Service.`,
    privacyContent: `1. Information We Collect
This Service can be used completely anonymously without registration or login. The data collected is minimized as follows:
• Anonymous ID: A random UUID generated on the client device, not linked to personal names, email addresses, or phone numbers.
• Vote Log: "Like" and "Skip" choice data entered during diagnosis, used to compile Like rates for each image.
• Diagnosis Result: Calculated results such as match rate and preference type.
• Device Info: Platform (iOS/Android/Web) used.

2. Purpose of Use
Collected anonymous information is used only for:
• Providing personalized preference results to users.
• Compiling statistics on Like rates and popular styles.
• Detecting bugs and improving UI/UX.

3. Ad Delivery and Data Use
We display ads via third-party providers (Google AdMob, Google AdSense, etc.). They may use anonymous identifiers (Cookies, IDFA/AAID) to display ads tailored to user interests. These can be disabled in browser or device privacy settings.

4. Data Deletion and Self-Management
Users can permanently delete all diagnosis history and anonymous vote logs synced to the database at any time from the "Settings" screen. Regenerating the anonymous ID completely severs connection with cloud data.

5. Contact Us
For questions regarding privacy and data deletion requests, please contact us via the in-app form.`,
  },
};
